version: '3.8'

services:
  backend:
    build: .
    container_name: shorturl_backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/iconstruye?authSource=admin
    volumes:
      - .:/app
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo_data:/data/db
      - ./src/config/data/init.dte.js:/docker-entrypoint-initdb.d/init-dte.js:ro
    restart: always

volumes:
  mongo_data:
